version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Run tests
          command: lein test

workflows:
  build:
    jobs:
      - build

