version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein

    steps:
      - checkout

      - restore_cache:
          key: v1-morph-{{ checksum "project.clj" }}

      - run:
          name: Install ant
          command: |
            if [ ! -d "${HOME}/ant" ]
            then
                curl -o ${HOME}/ant.tar.bz2 http://mirror.csclub.uwaterloo.ca/apache//ant/binaries/apache-ant-1.10.7-bin.tar.bz2
                tar jxf ${HOME}/ant.tar.bz2 -C ${HOME}
                mv ${HOME}/apache-ant-1.10.7 ${HOME}/ant
            fi

      - save_cache:
          key: v1-morph-{{ checksum "project.clj" }}
          paths:
            - ~/ant

      - run:
          name: Run tests
          command: |
            mkdir -p ~/test_output
            mkdir -p ~/artifacts
            mkdir -p ~/codox
            scripts/run_ci.sh

      - store_test_results:
          path: ~/test_output

      - store_artifacts:
          path: ~/artifacts

      - store_artifacts:
          path: ~/codox

      - deploy:
          name: Deploy master to clojars
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              lein deploy snapshots
            fi
