version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Run tests
          command: |
            mkdir -p ~/test_output
            mkdir -p ~/artifacts
            mkdir -p ~/codox
            scripts/run_ci.sh

      - store_test_results:
          path: ~/test_output

      - store_artifacts:
          path: ~/artifacts

      - store_artifacts:
          path: ~/codox

workflows:
  build:
    jobs:
      - build

